version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=what2do
      - POSTGRES_PASSWORD=what2do
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local